baseURL = "http://tobias.haerke.net/"
languageCode = "en-us"
title = "Tobias Haerke"
theme = "hallo-hugo-vervallsweg"
disableKinds = ["page", "section", "taxonomy", "taxonomyTerm"]

[Author]
    name = "Tobias Härke"

[params]

    [[params.links]]
        iconset = "fas"
        icon = "envelope"
        title = "E-mail"
        url = "mailto:tobias@haerke.net"

    [[params.links]]
        icon = "github"
        title = "Github"
        url = "https://github.com/vervallsweg"

    [[params.links]]
        icon = "twitter"
        title = "Twitter"
        url = "https://twitter.com/vervallsweg"
      
    [[params.links]]
        iconset = "fas"
        icon = "key"
        title = "E-mail"
        url = "https://keybase.io/vervallsweg"
